// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tK9sdP6G8aV8-w34T_bSewCJ3Z-9J0g',
    appId: '1:132402563298:web:d29abcb2ce3f7e1c35f6bb',
    messagingSenderId: '132402563298',
    projectId: 'points-2ebd5',
    authDomain: 'points-2ebd5.firebaseapp.com',
    storageBucket: 'points-2ebd5.firebasestorage.app',
    measurementId: 'G-F98QE8NK0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADey-KPtLtaghBDWJBp_bTfs2UKLeZG_U',
    appId: '1:132402563298:android:91c35676e6fcc81835f6bb',
    messagingSenderId: '132402563298',
    projectId: 'points-2ebd5',
    storageBucket: 'points-2ebd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhxmU1SZurqKOk0OJHIY9fLqfg3Otchk',
    appId: '1:132402563298:ios:423239f37bf1316835f6bb',
    messagingSenderId: '132402563298',
    projectId: 'points-2ebd5',
    storageBucket: 'points-2ebd5.firebasestorage.app',
    iosBundleId: 'com.example.pointSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhxmU1SZurqKOk0OJHIY9fLqfg3Otchk',
    appId: '1:132402563298:ios:423239f37bf1316835f6bb',
    messagingSenderId: '132402563298',
    projectId: 'points-2ebd5',
    storageBucket: 'points-2ebd5.firebasestorage.app',
    iosBundleId: 'com.example.pointSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9tK9sdP6G8aV8-w34T_bSewCJ3Z-9J0g',
    appId: '1:132402563298:web:9ef91594605ce5cc35f6bb',
    messagingSenderId: '132402563298',
    projectId: 'points-2ebd5',
    authDomain: 'points-2ebd5.firebaseapp.com',
    storageBucket: 'points-2ebd5.firebasestorage.app',
    measurementId: 'G-76FVS9G8BY',
  );
}
